############################################################
### Esta parte pertenece al entrenamiento del modelo GRU ###
############################################################

[GRUTrain]
#Numero de iteraciones para entrenar al modelo
EPOCHS = 100

#Tamaños de la capas ocultas
HIDDEN_SIZE = 64
#Numero de capas ocultas
NUM_LAYERS = 1

BATCH_SIZE = 32
LEARNING_RATE = 0.001
ACCURACY_THRESHOLD = 0.1

USE_CUDA = True




#############################################################
### Esta parte pertenece al entrenamiento del Autoencoder ###
#############################################################

[Autoencoder]
#Numero final de secuencias sinteticas que se generaran
N_SYNTHETIC = 1000

#Numero de iteraciones para entrenar al autoencoder
AE_EPOCHS = 160
#Numero de iteraciones para entrenar al modelo GRU para generar las salidas
GRU_EPOCHS = 100

#Tamaños de la capas latentes del autoencoder
LATENT_SIZE = 32
#Tamaños de la capas ocultas del modelo GRU
HIDDEN_SIZE = 64
#Numero de capas ocultas
NUM_LAYERS = 1

LEARNING_RATE = 0.001
LATENT_NOISE_STD = 0.1
BATCH_SIZE = 32

USE_CUDA = True



##########################################################
### Esta parte pertenece a las propiedades del dataset ###
##########################################################

[Dataset]

#Nombre del dataset
CSV_NAME = dataset.csv

#Nombre del dataset que usara el gru_tester.py
TESTER_CSV_NAME = realset.csv

#Numero de columnas de salida
OUTPUT_NAMES = Ira,Miedo,Felicidad,Tristeza,Sorpresa,Disgusto

#Longitud de la secuencia
SEQUENCE_LENGTH = 35

#Tamaño de los bloques de secuencias contiguas del dataset
BLOCK_SIZE = 46
